### ISSUE TITLE
Error executing generate.py

### ISSUE THREAD

**Issue by Dikakus** [Sg4Dylan/FLAD#1]
Hi. I'm trying to test your software to check some flac files. I put a flac file in /home/music and launched

python3 generate.py 

But I got theese errors:

TypeError: get_spectrum() got an unexpected keyword argument 'noise'
Process Process-5:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/app/FLAD/generate.py", line 18, in do
    utils.get_spectrum(y_s, idx, dst_path, noise=[0.001, 0.01])

**Comment by Sg4Dylan** [comment]
Thank you for your feedback, the problem has been fixed
